"""NL -> gold SQL eval set for the toy shop DB.

Each task: {id, level, split, question, gold}.
  level: easy | medium | hard
  split: train (optimize on these) | test (held-out, honest reporting)

The train/test split is deliberate: Reflexion, SkillOpt and friends must improve
on train WITHOUT peeking at test. The test number is the one we trust.
"""

TASKS = [
    # ---------------- easy ----------------
    {"id": 1, "level": "easy", "split": "train",
     "question": "List the names of all customers in Mumbai.",
     "gold": "SELECT name FROM customers WHERE city='Mumbai';"},
    {"id": 2, "level": "easy", "split": "train",
     "question": "How many customers are there in total?",
     "gold": "SELECT COUNT(*) FROM customers;"},
    {"id": 3, "level": "easy", "split": "test",
     "question": "Show all product names in the Electronics category.",
     "gold": "SELECT name FROM products WHERE category='Electronics';"},
    {"id": 4, "level": "easy", "split": "train",
     "question": "What is the price of the product named 'Running Shoes'?",
     "gold": "SELECT price FROM products WHERE name='Running Shoes';"},
    {"id": 5, "level": "easy", "split": "test",
     "question": "List all distinct cities where customers live.",
     "gold": "SELECT DISTINCT city FROM customers;"},
    {"id": 6, "level": "easy", "split": "train",
     "question": "How many orders have status 'completed'?",
     "gold": "SELECT COUNT(*) FROM orders WHERE status='completed';"},
    {"id": 7, "level": "easy", "split": "train",
     "question": "Show the names of products that cost more than 2000.",
     "gold": "SELECT name FROM products WHERE price>2000;"},
    {"id": 8, "level": "easy", "split": "test",
     "question": "List the names of customers in the Enterprise segment.",
     "gold": "SELECT name FROM customers WHERE segment='Enterprise';"},
    {"id": 9, "level": "easy", "split": "test",
     "question": "How many products are in the Books category?",
     "gold": "SELECT COUNT(*) FROM products WHERE category='Books';"},
    {"id": 10, "level": "easy", "split": "train",
     "question": "List all order ids that have status 'cancelled'.",
     "gold": "SELECT order_id FROM orders WHERE status='cancelled';"},

    # ---------------- medium ----------------
    {"id": 11, "level": "medium", "split": "train",
     "question": "For each customer who placed at least one order, show their name and the number of orders they placed.",
     "gold": "SELECT c.name, COUNT(*) FROM customers c JOIN orders o ON o.customer_id=c.customer_id GROUP BY c.customer_id, c.name;"},
    {"id": 12, "level": "medium", "split": "test",
     "question": "What is the average product price per category? Return category and average price.",
     "gold": "SELECT category, AVG(price) FROM products GROUP BY category;"},
    {"id": 13, "level": "medium", "split": "train",
     "question": "List the top 3 most expensive products with their name and price, most expensive first.",
     "gold": "SELECT name, price FROM products ORDER BY price DESC LIMIT 3;"},
    {"id": 14, "level": "medium", "split": "test",
     "question": "How many orders were placed in each month of 2025? Return the month and the count.",
     "gold": "SELECT strftime('%m', order_date) AS m, COUNT(*) FROM orders GROUP BY m;"},
    {"id": 15, "level": "medium", "split": "train",
     "question": "Which cities have more than 2 customers? Return the city and the customer count.",
     "gold": "SELECT city, COUNT(*) FROM customers GROUP BY city HAVING COUNT(*)>2;"},
    {"id": 16, "level": "medium", "split": "test",
     "question": "List the names of products that have never been ordered.",
     "gold": "SELECT name FROM products WHERE product_id NOT IN (SELECT DISTINCT product_id FROM order_items);"},
    {"id": 17, "level": "medium", "split": "train",
     "question": "Count the number of orders per status. Return status and count.",
     "gold": "SELECT status, COUNT(*) FROM orders GROUP BY status;"},
    {"id": 18, "level": "medium", "split": "test",
     "question": "What is the total quantity ordered for each product? Return the product name and total quantity.",
     "gold": "SELECT p.name, SUM(oi.quantity) FROM products p JOIN order_items oi ON oi.product_id=p.product_id GROUP BY p.product_id, p.name;"},
    {"id": 19, "level": "medium", "split": "train",
     "question": "List the names of customers who signed up on or after 1 July 2024.",
     "gold": "SELECT name FROM customers WHERE signup_date >= '2024-07-01';"},
    {"id": 20, "level": "medium", "split": "train",
     "question": "How many distinct products were ordered in completed orders?",
     "gold": "SELECT COUNT(DISTINCT oi.product_id) FROM order_items oi JOIN orders o ON o.order_id=oi.order_id WHERE o.status='completed';"},

    # ---------------- hard ----------------
    {"id": 21, "level": "hard", "split": "train",
     "question": "What is the total completed revenue, where revenue of a line item is quantity times product price and only orders with status 'completed' count?",
     "gold": "SELECT SUM(oi.quantity*p.price) FROM order_items oi JOIN orders o ON o.order_id=oi.order_id JOIN products p ON p.product_id=oi.product_id WHERE o.status='completed';"},
    {"id": 22, "level": "hard", "split": "test",
     "question": "Which product generated the most completed revenue? Return only the product name.",
     "gold": "SELECT p.name FROM order_items oi JOIN orders o ON o.order_id=oi.order_id JOIN products p ON p.product_id=oi.product_id WHERE o.status='completed' GROUP BY p.product_id, p.name ORDER BY SUM(oi.quantity*p.price) DESC LIMIT 1;"},
    {"id": 23, "level": "hard", "split": "train",
     "question": "What is the total completed revenue per product category? Return category and revenue, highest revenue first.",
     "gold": "SELECT p.category, SUM(oi.quantity*p.price) AS rev FROM order_items oi JOIN orders o ON o.order_id=oi.order_id JOIN products p ON p.product_id=oi.product_id WHERE o.status='completed' GROUP BY p.category ORDER BY rev DESC;"},
    {"id": 24, "level": "hard", "split": "test",
     "question": "Which customer has the highest total completed revenue? Return only the customer name.",
     "gold": "SELECT c.name FROM order_items oi JOIN orders o ON o.order_id=oi.order_id JOIN customers c ON c.customer_id=o.customer_id JOIN products p ON p.product_id=oi.product_id WHERE o.status='completed' GROUP BY c.customer_id, c.name ORDER BY SUM(oi.quantity*p.price) DESC LIMIT 1;"},
    {"id": 25, "level": "hard", "split": "train",
     "question": "For each customer segment, what is the total completed revenue? Return segment and revenue.",
     "gold": "SELECT c.segment, SUM(oi.quantity*p.price) FROM order_items oi JOIN orders o ON o.order_id=oi.order_id JOIN customers c ON c.customer_id=o.customer_id JOIN products p ON p.product_id=oi.product_id WHERE o.status='completed' GROUP BY c.segment;"},
    {"id": 26, "level": "hard", "split": "train",
     "question": "List the top 5 customers by number of orders, with name and order count, most orders first.",
     "gold": "SELECT c.name, COUNT(*) AS n FROM customers c JOIN orders o ON o.customer_id=c.customer_id GROUP BY c.customer_id, c.name ORDER BY n DESC LIMIT 5;"},
    {"id": 27, "level": "hard", "split": "test",
     "question": "What is the average order value (average total revenue per order) across completed orders?",
     "gold": "SELECT AVG(order_rev) FROM (SELECT o.order_id, SUM(oi.quantity*p.price) AS order_rev FROM orders o JOIN order_items oi ON oi.order_id=o.order_id JOIN products p ON p.product_id=oi.product_id WHERE o.status='completed' GROUP BY o.order_id);"},
    {"id": 28, "level": "hard", "split": "train",
     "question": "Which city generated the most completed revenue? Return only the city.",
     "gold": "SELECT c.city FROM order_items oi JOIN orders o ON o.order_id=oi.order_id JOIN customers c ON c.customer_id=o.customer_id JOIN products p ON p.product_id=oi.product_id WHERE o.status='completed' GROUP BY c.city ORDER BY SUM(oi.quantity*p.price) DESC LIMIT 1;"},
    {"id": 29, "level": "hard", "split": "train",
     "question": "List the names of customers who have never placed an order.",
     "gold": "SELECT name FROM customers WHERE customer_id NOT IN (SELECT DISTINCT customer_id FROM orders);"},
    {"id": 30, "level": "hard", "split": "test",
     "question": "What is the most popular product category by total quantity ordered across all orders? Return only the category.",
     "gold": "SELECT p.category FROM order_items oi JOIN products p ON p.product_id=oi.product_id GROUP BY p.category ORDER BY SUM(oi.quantity) DESC LIMIT 1;"},
    {"id": 31, "level": "hard", "split": "train",
     "question": "How many orders contain more than 2 line items?",
     "gold": "SELECT COUNT(*) FROM (SELECT order_id FROM order_items GROUP BY order_id HAVING COUNT(*)>2);"},
    {"id": 32, "level": "hard", "split": "train",
     "question": "For each month in 2025, what is the total completed revenue? Return month and revenue ordered by month.",
     "gold": "SELECT strftime('%m', o.order_date) AS m, SUM(oi.quantity*p.price) AS rev FROM orders o JOIN order_items oi ON oi.order_id=o.order_id JOIN products p ON p.product_id=oi.product_id WHERE o.status='completed' GROUP BY m ORDER BY m;"},
    {"id": 33, "level": "hard", "split": "test",
     "question": "Which products have an average ordered quantity greater than 2? Return the product name.",
     "gold": "SELECT p.name FROM order_items oi JOIN products p ON p.product_id=oi.product_id GROUP BY p.product_id, p.name HAVING AVG(oi.quantity)>2;"},
    {"id": 34, "level": "hard", "split": "train",
     "question": "List the names of customers who have at least one cancelled order.",
     "gold": "SELECT DISTINCT c.name FROM customers c JOIN orders o ON o.customer_id=c.customer_id WHERE o.status='cancelled';"},
    {"id": 35, "level": "hard", "split": "train",
     "question": "What fraction of all orders were returned? Return a single number (returned orders divided by total orders).",
     "gold": "SELECT (SELECT COUNT(*) FROM orders WHERE status='returned')*1.0/(SELECT COUNT(*) FROM orders);"},
    {"id": 36, "level": "hard", "split": "test",
     "question": "Find the most expensive product in each category. Return the category and the product name.",
     "gold": "SELECT p.category, p.name FROM products p JOIN (SELECT category, MAX(price) mx FROM products GROUP BY category) m ON m.category=p.category AND p.price=m.mx;"},
    {"id": 37, "level": "hard", "split": "train",
     "question": "How many customers placed orders in more than one distinct month of 2025?",
     "gold": "SELECT COUNT(*) FROM (SELECT customer_id FROM orders GROUP BY customer_id HAVING COUNT(DISTINCT strftime('%m', order_date))>1);"},
    {"id": 38, "level": "hard", "split": "test",
     "question": "Which customer segment has the highest average completed order value? Return only the segment.",
     "gold": "SELECT seg FROM (SELECT c.segment AS seg, AVG(t.order_rev) AS aov FROM (SELECT o.order_id, o.customer_id, SUM(oi.quantity*p.price) AS order_rev FROM orders o JOIN order_items oi ON oi.order_id=o.order_id JOIN products p ON p.product_id=oi.product_id WHERE o.status='completed' GROUP BY o.order_id) t JOIN customers c ON c.customer_id=t.customer_id GROUP BY c.segment ORDER BY aov DESC LIMIT 1);"},
    {"id": 39, "level": "hard", "split": "train",
     "question": "List the names of products that were never ordered in a completed order.",
     "gold": "SELECT name FROM products WHERE product_id NOT IN (SELECT oi.product_id FROM order_items oi JOIN orders o ON o.order_id=oi.order_id WHERE o.status='completed');"},
    {"id": 40, "level": "hard", "split": "test",
     "question": "Return the total revenue across all orders and the completed-only revenue, as two columns.",
     "gold": "SELECT SUM(oi.quantity*p.price) AS total_rev, SUM(CASE WHEN o.status='completed' THEN oi.quantity*p.price ELSE 0 END) AS completed_rev FROM order_items oi JOIN orders o ON o.order_id=oi.order_id JOIN products p ON p.product_id=oi.product_id;"},
]
